[quant-ph]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "quant-ph"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"

[hep-ex]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "hep-ex"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"

[hep-lat]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "hep-lat"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"

[hep-ph]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "hep-ph"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"

[hep-th]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "hep-th"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"

[chem-ph]
advanced = ""
terms-0-term = ""
terms-0-operator = "AND"
terms-0-field = "title"
classification-physics = "y"
classification-physics_archives = "physics"
classification-include_cross_list = "include"
date-filter_by = "date_range"
date-year = ""
date-from_date = "2025-02-01"
date-to_date = "2025-02-02"
date-date_type = "submitted_date_first"
abstracts = "show"
size = "200"
order = "submitted_date"
terms-1-operator = "AND"
terms-1-term = "physics.chem-ph"
terms-1-field = "all"
